[package]
name        = "valua-polyfills"
description = "Embedded Lua polyfill strings for Lua 5.5 → 5.1 transpilation"
edition.workspace     = true
version.workspace     = true
authors.workspace     = true
license.workspace     = true
rust-version.workspace = true

[dependencies]

[dev-dependencies]
pretty_assertions = { workspace = true }
