[package]
name        = "valua-core"
description = "Orchestrates the full valua transpile pipeline (lex → parse → transform → codegen)"
edition.workspace     = true
version.workspace     = true
authors.workspace     = true
license.workspace     = true
rust-version.workspace = true

[dependencies]
valua-diagnostics = { workspace = true }
valua-ast         = { workspace = true }
valua-lexer       = { workspace = true }
valua-parser      = { workspace = true }
valua-transformer = { workspace = true }
valua-codegen     = { workspace = true }
valua-polyfills   = { workspace = true }
thiserror         = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
insta             = { workspace = true }
