[package]
name        = "valua-lexer"
description = "Lua 5.5 tokenizer for the valua transpiler (Lua 5.4 is a supported subset)"
edition.workspace     = true
version.workspace     = true
authors.workspace     = true
license.workspace     = true
rust-version.workspace = true

[dependencies]
valua-diagnostics = { workspace = true }
logos             = { workspace = true }
thiserror         = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
insta             = { workspace = true }
